
spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pratice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  profiles:
    active: dev
server:
  port: 20000
mybatis:
  #mapper-locations: classpath:com/pratice/mybatispro/mapper/*Mapper.xml
  mapper-locations: mapper/*.xml
  type-aliases-package: com.pratice.mybatispro.pojo
  configuration:
    #javebean成员变量名自动转驼峰
    map-underscore-to-camel-case: true
